# Generated by Django 5.2.4 on 2025-07-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("surname", models.CharField(max_length=100, verbose_name="Surname")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
            ],
        ),
    ]
